version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - pip install -g aws-sam-cli 
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name todo-app-stack --capabilities CAPABILITY_IAM --region eu-north-1

artifacts:
  files:
    - template.yaml
    - '**/*'
